steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'NetWorthCalc.Web/Client'

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test']
  dir: 'NetWorthCalc.Web/Client'
  env: ['CI=true']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'NetWorthCalc.Web/Client'

- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  entrypoint: 'dotnet'
  args: ['publish', '-c', 'Release']
  env: ['DOTNET_CLI_TELEMETRY_OPTOUT=true']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml']
  dir: 'NetWorthCalc.Web/bin/Release/netcoreapp3.1/publish'

timeout: 720s # 12 minutes
