steps:
- name: 'microsoft/dotnet:sdk'
  entrypoint: 'dotnet'
  args: ['--version']

- name: 'microsoft/dotnet:sdk'
  entrypoint: 'dotnet'
  args: ['restore']

- name: 'microsoft/dotnet:sdk'
  entrypoint: 'dotnet'
  args: ['publish', '-c', 'Release']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: 'ReactStarter.Web/bin/Release/netcoreapp3.1/publish'
