steps:
- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  entrypoint: 'dotnet'
  args: ['publish', '-c', 'Release']

- name: 'node'
  entrypoint: 'npm'
  args: ['install']
  dir: 'ReactStarter.Web/Client'

- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'test']
  dir: 'ReactStarter.Web/Client'
  env: ['CI=true']

- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'build']
  dir: 'ReactStarter.Web/Client'

- name: 'bash'
  args: ['mkdir', 'ReactStarter.Web/bin/Release/netcoreapp3.1/publish/Client/build']

- name: 'bash'
  args: ['mv', 'build/*', '../bin/Release/netcoreapp3.1/publish/Client/build']
  dir: 'ReactStarter.Web/Client'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml']
  dir: 'ReactStarter.Web/bin/Release/netcoreapp3.1/publish'
