steps:
- name: 'gcr.io/cloud-builders/dotnet'
  args: ['restore']

- name: 'gcr.io/cloud-builders/dotnet'
  args: ['publish', '-c', 'Release']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml']
  dir: 'ReactStarter.Web/bin/Release/netcoreapp3.1/publish'
